export const API_BREED_LIST_REQUEST = "API_BREED_LIST_REQUEST";
export const API_BREED_LIST_SUCCESS = 'API_BREED_LIST_SUCCESS';
export const API_BREED_LIST_FAILURE = 'API_BREED_LIST_FAILURE';
export const API_BREED_REQUEST = "API_BREED_REQUEST";
export const API_BREED_SUCCESS = 'API_BREED_SUCCESS';
export const API_BREED_FAILURE = 'API_BREED_FAILURE';